@startuml
title <color:red><b>4.1.3 用例“为客户下单”细化图</b></color>

actor 收银员 as Cashier

Cashier --> (为客户下单)

(为客户下单) --> (选择物品种类) : <<include>>
(为客户下单) --> (选择服务类型) : <<include>>
(为客户下单) --> (计算订单价格) : <<include>>
(为客户下单) --> (预计取衣时间) : <<include>>
(为客户下单) --> (保存订单信息) : <<include>>
@enduml
